FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-build 

#RUN install_packages python-pip3

RUN pip install w1thermsensor
RUN pip install adafruit-circuitpython-dht

# Defines our working directory in container
WORKDIR /usr/src/app

# This will copy all files in our root to the working  directory in the container
#COPY . ./


COPY ./entry.sh /usr/src/app/
RUN chmod +x /usr/src/app/entry.sh
CMD ["./entry.sh"]
