version: '2'
volumes:
    home-data:
services:
  read_sensor:
    build: ./read_sensor
    privileged: true
    restart: always
    volumes:
      - 'home-data:/data'
  influxdb:
    restart: always
    build: ./influxdb
    volumes:
      - 'home-data:/data'
  telegraf:
    build: ./telegraf
    restart: always
    cap_add:
      - SYS_ADMIN
  mqtt:
    image: arm32v6/eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always
    